type: rails
build:
  app:
    port: 9292
    env:
    - name: REDIS_HOST
      value: 127.0.0.1
  containers:
  - image: mysql:5.6
    name: db
    env:
    - name: HOGE_ENV
      value: hogehoge

  before_run_app:
    command: ["cp", "config/dummy.sample", "config/dummy"]
    
benchmark:
  target_paths:
  - /
  - /articles
